apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-metrics
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-metrics
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["metrics.k8s.io"]
  resources: ["pods"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pod-metrics
subjects:
- kind: ServiceAccount
  name: pod-metrics
  namespace: default
roleRef:
  kind: ClusterRole
  name: pod-metrics
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-metrics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod-metrics
  template:
    metadata:
      labels:
        app: pod-metrics
    spec:
      serviceAccountName: pod-metrics
      containers:
      - name: collector
        image: pod-metrics:latest
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: "100m"      # Request 0.1 CPU cores
            memory: "128Mi"   # Request 128MB memory
          limits:
            cpu: "500m"      # Limit to 0.5 CPU cores
            memory: "256Mi"   # Limit to 256MB memory
        volumeMounts:
        - name: config-volume
          mountPath: /etc/config
      volumes:
      - name: config-volume
        configMap:
          name: pod-metrics-config