apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-metrics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod-metrics
  template:
    metadata:
      labels:
        app: pod-metrics
    spec:
      containers:
      - name: collector
        image: pod-metrics:latest
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        volumeMounts:
        - name: config-volume
          mountPath: /etc/config
        - name: secrets-volume
          mountPath: /etc/secrets
          readOnly: true
      volumes:
      - name: config-volume
        configMap:
          name: pod-metrics-config
      - name: secrets-volume
        secret:
          secretName: pod-metrics-secrets